### ISSUE TITLE
ServerRuntimeFactory hardcoded inside CayenneModule

### ISSUE THREAD

**Issue by IRus** [bootique/bootique-cayenne#64]
I'd like to produce my own instance of `ServerRuntimeFactory` for `CayenneModule` by overriding it, but it's not possible, since service locator pattern [used](https://github.com/bootique/bootique-cayenne/blob/master/bootique-cayenne/src/main/java/io/bootique/cayenne/CayenneModule.java#L87) inside this module. `ServerRuntimeFactory` should be injected in `createCayenneRuntime` function.

**Comment by andrus** [comment]
The argument against making factories injectable (even though we occasionally do it), is that factories are mutable, and hence making them globally accessible singletons is unsafe and may give users wrong ideas :)

So while 3bb26ca solves the issue as described, perhaps a better solution would be to make the factory polymorphic, so anyone can still redefine it, but using configuration instead of injection?

**Comment by IRus** [comment]
Maybe, or factory can be immutable interface. At least, now this module aligned with others.

**Comment by andrus** [comment]
> this module aligned with others

Which ones?

**Comment by IRus** [comment]
* https://github.com/bootique/bootique-jersey-client/blob/master/bootique-jersey-client/src/main/java/io/bootique/jersey/client/JerseyClientModule.java#L53
* https://github.com/bootique/bootique-metrics/blob/master/bootique-metrics/src/main/java/io/bootique/metrics/MetricsModule.java#L50
* https://github.com/bootique/bootique-jetty/blob/master/bootique-jetty/src/main/java/io/bootique/jetty/JettyModule.java#L170

**Comment by andrus** [comment]
Yeah, those are the ones where we had to do it for the lack of a better solution. The motivation there was NOT to allow overriding the factory via DI, but for a few different reasons:

*  To ensure the factory is a singleton if it produces more than one service and needs to be shared between multiple service provider methods. 
* Complex (deferred, circular) service initialization flow in metrics.

I still feel we shouldn't propagate this pattern for the purposes of overriding.
